# Config for running the InferenceRecipe in generate.py to generate output
# from Llama2 7B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-2-7b-hf --output-dir /tmp/Llama-2-7b-hf --ignore-patterns "*.safetensors" --hf-token <HF_TOKEN>
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

output_dir: /tmp/torchtune/qwen2_5_3B_blt/generate

# Model arguments
model:
  _component_: ttblt.bltqwen.qwen2_5_blt

checkpointer:
  _component_: torchtune.training.FullModelMetaCheckpointer
  checkpoint_dir: /tmp/torchtune/qwen2_5_3B_blt/full_single_device/epoch_3
  checkpoint_files: [
    adapter_model.pt
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: REWARD

device: cuda:1
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: ttblt.bltqwen.blt_tokenizer
  max_seq_len: 4096

# Generation arguments; defaults taken from gpt-fast
prompt:
  system: null
  user: "Tell me a joke.\n"
max_new_tokens: 300
temperature: 0.3
top_k: 25 # Smaller, bytes! 

enable_kv_cache: False # Issue with cross-attention

quantizer: null
